# Generated by Django 4.0.6 on 2022-07-27 15:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.IntegerField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
