# Generated by Django 4.0.6 on 2022-07-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_basemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
